### ISSUE TITLE
Error occurred when I load HED model using keras.models.load_model(.h5)

### ISSUE THREAD

**Issue by yeongkwoncho** [lc82111/Keras_HED#9]
Hello~
I have trained and tested this HED model.
In conclusion, I have confirmed this model works fine and very good.
I saved the model as .h5 format using model.save('hed.h5').
**Then, I have tried to load the saved model again using keras.models.load_model('hed.h5').**
But the error occurred like: 
**ValueError: Unknown loss function:cross_entropy_balanced**

How can I get over this?

**(detailed error message)**
Traceback (most recent call last):

  File "<ipython-input-170-205d4233a151>", line 1, in <module>
    model0 = keras.models.load_model('hed.h5')

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\saving.py", line 369, in _deserialize_model
    sample_weight_mode=sample_weight_mode)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\training.py", line 119, in compile
    self.loss, self.output_names)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\training_utils.py", line 820, in prepare_loss_functions
    loss_functions.append(get_loss_function(loss.get(name, None)))

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\engine\training_utils.py", line 705, in get_loss_function
    loss_fn = losses.get(loss)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\losses.py", line 795, in get
    return deserialize(identifier)

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\losses.py", line 776, in deserialize
    printable_module_name='loss function')

  File "C:\Anaconda3\lib\site-packages\keras-2.3.0-py3.6.egg\keras\utils\generic_utils.py", line 167, in deserialize_keras_object
    ':' + function_name)

ValueError: Unknown loss function:cross_entropy_balanced

**Comment by yeongkwoncho** [comment]
I have solved this problem myself. So, closed.
